spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:apidb}
    username: ${DB_USER:apiuser}
    password: ${DB_PASS:apipass}
  data:
    redis:
      host: ${CACHE_HOST:localhost}
      port: ${CACHE_PORT:6379}
      password: ${CACHE_PASS:}
logging:
  level:
    com.example.blog.repository   : DEBUG
    org.springframework.security: TRACE
    org.springframework.data.redis: TRACE
    org.springframework.session: TRACE
  server:
    servlet:
      session:
        timeout: 300s # 実験用にとても短い30秒に設定
aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:4566}
    region: ${AWS_S3_REGION:ap-northeast-1}
    access-key: ${AWS_S3_ACCESS_KEY:test1}
    secret-key: ${AWS_S3_SECRET_KEY:test2}
    bucket:
      profile-images: ${AWS_S3_BUCKET_PROFILE_IMAGES:profile-images}